# Generated by Django 5.2.12 on 2026-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='guid_1c',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='GUID в 1С'),
        ),
        migrations.AlterField(
            model_name='client',
            name='guid_1c',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='GUID в 1С'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='guid_1c',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='GUID в 1С'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guid_1c',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='GUID в 1С'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='guid_1c',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='GUID в 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid_1c',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='GUID в 1С'),
        ),
    ]
