# Generated by Django 5.2.12 on 2026-04-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_client_user_client_unique_client_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
